title: Plank w/ wheels
description: >
  Personal thoughts about skateboarding
baseurl: "/lisaskates"
url: "https://blake1ward.github.io/lisaskates"
paginate:	2 # The number of posts to show per page on your homepage
name: "Lisa"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
