title: Skate Blog
description: >
  I'm just a MILF who loves to shred
baseurl: "/immaculate"
url: "https://github.com/siawyoung/immaculate"
paginate:	2 # The number of posts to show per page on your homepage
name: "Lisa"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
